### PR TITLE
Installation file move into docs/user/metacat/source

### PR DESCRIPTION
**Pull request by yvanlebras**
If I'm not wrong ;)

### CODE REVIEW

**Comment by yvanlebras** [comment]
Thank you for your feedback. It seems to me there is no docs/install.html ? That's why I was searching towards src... I'm wrong?

**Comment by taojing2002** [comment]
The "doc/install.html" references a relative html path of a installed 
Metacat. See you can find it at:
https://knb.ecoinformatics.org/knb/docs/install.html

**Comment by yvanlebras** [comment]
Ooops. Really sorry... I understand now. Thank you!

**Comment by taojing2002** [comment]
You are welcome. Thank you every much for your effort to improve Metacat!

**Pull request closed without merging**
