### PR TITLE
stopped aborting startup when in container/k8s if site props is r/o 

### PR DESCRIPTION
**Pull request by artntek**
stopped aborting startup when in container/k8s if site props is r/o (expected in that environment)

### CODE REVIEW

**Review by taojing2002 — APPROVED** [review]
It looks good!

**Review by mbjones — APPROVED** [review]
Took a quick look, overall looks good. 

In the comments you state that this checks if `/var/metacat` is writable, but I don't immediately see where that is checked. It would be good to check it, as even in k8s we need that writable volume to be in place for data to be written.

**Comment by artntek** [comment]
> In the comments you state that this checks if `/var/metacat` is writable, but I don't immediately see where that is checked. It would be good to check it, as even in k8s we need that writable volume to be in place for data to be written.

Unfortunately, the comments are misleading. When the app is starting up, we don't know for sure that /var/metacat/ is the location for the metacat files (since that's configurable). (We do know it's /var/metacat in k8s, because that's hardcoded into the image, but we also create those directories in `docker-entrypoint.sh`, thus guaranteeing they are there (or startup fails).

If you want me to add validation for /var/metacat being writeable only when running in a container, I'm happy to do that, but since that's checked elsewhere, a simpler approach would be to change the comments so they aren't misleading, and leave the code as is. 

LMK which you prefer.

**Comment by mbjones** [comment]
Fixing the comments for now is fine. As you say in that class documentation, there are more checks to be added later.

**Pull request merged**
