### PR TITLE
Add EML 2.2.0 support

### PR DESCRIPTION
**Pull request by amoeba**
@taojing2002 	could you have a look at this?

- Updated xml catalog and Ant build to pull in EML 2.2.0 schema
- View service support (Structured funding, annotations, Markdown)
- Updated metacat-index to support EML 2.2.0
  - New schema fields to support generic funding and structured funding information in EML
  - New EML 2.2.0 context file
  - New `EMLAnnotationSubprocessor` to handle Annotations in EML 2.2.0 records
  - New `OntologyModelService` that provides a convenient way to perform query expansion. This is faster and safer than how we were doing this before.
  - Refactored `AnnotatorSubprocessor` to use `OntologyModelService`
- Added `funding` field into all relevant EML subprocessor context files

Two things I could use a second set of eyes on are:

- I had to do funky things to handle file paths under deployment and test scenarios that I didn't like, but it works: https://github.com/NCEAS/metacat/compare/dev-2.11...feature-eml220-support?expand=1#diff-149dbdbb16c8d13ffe6afd167d9aac0dR171. Can this be simpler or more idiomatic?
- I bumped this dep to match the state of the 2.3 branch of that project but I'm not entirely sure I had to since we duplicate most of the relevant indexing code I added into `metacat-index` so it may work on previous versions.
    ```
    <d1_cn_index_processor_version>2.3.10</d1_cn_index_processor_version>
    ```

### CODE REVIEW

**Comment by amoeba** [comment]
When I created this there were two conflicts. `lib/style/skins/metacatui/eml-2/eml-dataset.xsl` is an easy fix, but with `metacat-index/pom.xml`, I bumped d1_cn_index_processor_version` and you had bumped `metacat_common_version`.

Should we just bump them both?

```xml
<d1_cn_index_processor_version>2.3.10</d1_cn_index_processor_version>
<metacat_common_version>2.10.4</metacat_common_version>
```

**Comment by amoeba** [comment]
Thanks, @taojing2002! Did I do that correctly in https://github.com/NCEAS/metacat/pull/1375/files#diff-88fc5c1ff252e5c4d897affd893019d4?

**Comment by taojing2002** [comment]
Hi @amoeba Would you please give a specific file link about the file path test? Your link only shows a list of commits you did on this branch.

**Comment by taojing2002** [comment]
Thanks for the replying. I looked at code and it seems we need to added 
the newest hash `20ccd7b01985707bfc870f27713f859f` to the list of 
previous hash as well.

**Comment by amoeba** [comment]
For me, the link goes right to the line. But the diff is:

```patch
-index.schema.previous.hash=714457a3cdd05e034e5df46589b3bfa9;ba7dc67bbf749b02e03d7b7cc6a31def;ebf5b20f9cd18d31c3a6057749ba9397;fb1f63a36f2c742f1ba144d559c37075;2acacecbb55721806b7e92d7a115c35a;3418ed9d10bbc70f1e8020233d954f83;a54e667426384f89106405263df77373;8fc703ec01ef6d4cb413d9c2fbced532;25f1b66f3a25e1c80adf86e48f1838bb;1a0f05c01c5714737a1efc992b262e7e;8b18d7ed4a5364159adeb507f004e5de
+index.schema.previous.hash=8b18d7ed4a5364159adeb507f004e5de;714457a3cdd05e034e5df46589b3bfa9;ba7dc67bbf749b02e03d7b7cc6a31def;ebf5b20f9cd18d31c3a6057749ba9397;fb1f63a36f2c742f1ba144d559c37075;2acacecbb55721806b7e92d7a115c35a;3418ed9d10bbc70f1e8020233d954f83;a54e667426384f89106405263df77373;8fc703ec01ef6d4cb413d9c2fbced532;25f1b66f3a25e1c80adf86e48f1838bb;1a0f05c01c5714737a1efc992b262e7e
#The md5 hash number for the schema.xml in this release
-index.schema.current.hash=8b18d7ed4a5364159adeb507f004e5de
+index.schema.current.hash=20ccd7b01985707bfc870f27713f859f
```

**Comment by amoeba** [comment]
@taojing2002 mentioned on Slack that I needed to add the current hash to the list of previous hashes as well so I made that change.

@taojing2002 	this is all set to merge. Thanks for taking a look at it.

**Pull request merged**
