### PR TITLE
Write a script to auto detect maven.home in the ant build

### PR DESCRIPTION
**Pull request by amoeba**
This was annoying to set every time I ran the ant build and it seemed like something that could be automated. I figured out how. Hopefully addresses #1242 satisfactorally.

### CODE REVIEW

**Comment by mbjones** [comment]
Awesome. Glad it was improved. Certainly a huge step up from the build property, which I agree was so annoying.

Does it work on windows?  Seems like the same functional tests could have been implemented in Ant rather than bash -- first use Ant to test if the env var exists, and if not, then use ant's `exec` task to start the mvn executable and capture the output to set the MAVEN_HOME env var.  Its probably good enough to commit this as is, but it would be nice to keep the Windows build working. Let's discuss.

**Comment by amoeba** [comment]
> Does it work on windows? Seems like the same functional tests could have been implemented in Ant rather than bash

I'm pretty sure it wouldn't work (outside of WSL) since I hardcode `/bin/sh`. Doing this in Ant is beyond me at the moment so doing this via a shell script was a lot faster for me. I'd be happy to see this done entirely in Ant so we can support Windows.

I don't think I have the time to invest right now to learn enough Ant to make this work. Maybe somebody else could bang this out in Ant real quick?

**Comment by taojing2002** [comment]
In the find-maven.sh script file, is it possible to handle the command `mvn3`? In my mac, I only have the `mvn3` command.

**Comment by amoeba** [comment]
I don't see why not @taojing2002. Just curious, what install method gave you a `mvn3` executable?

**Comment by amoeba** [comment]
@taojing2002 thanks 👍 . What did you think about @mbjones 's idea to in-line this into the ant build rather than putting this in as separate file? Any chance you're experienced writing Ant tasks?

**Comment by amoeba** [comment]
I decided to convert my previous shell script into a proper ant ask. I force-pushed the branch and re-based it off of `dev-2.10` so any code you saw before is gone.I think I like ant more than I expected.

@taojing2002 can you give this a whirl some time? It should just work for you out of the box so long as the shell you call `ant` from can see a `mvn3` executable. You should then be able to override the value by adding `maven.home` to `build.properties` or setting a `$MAVEN_HOME` env var.

The new behavior is:

- Trust `maven.home	`
- Fall back to `$MAVEN_HOME`
- Fall back to asking `mvn3` and then `mvn` to print its home to stdout and capture it
- Fail the task if `maven.home` isn't set to something after all of this

**Comment by taojing2002** [comment]
This is great. However, when I tried this branch on mn-demo-6.test.dataone.org,  which we always use as a test server, it didn't work. I think other demo machines don't work either. Is it possible to make this case work out of box?

**Comment by amoeba** [comment]
Thanks for checking it out. 

> Is it possible to make this case work out of box?

Most definitely. 

Re:

> it didn't work

What behavior do you see? What kind of system is that?

**Comment by taojing2002** [comment]
The mn-demo-6 was just upgraded to Ubuntu 18.04 and the maven was removed. After I reinstall maven, it works. My bad.

However, the branch doesn't work with Ubuntu 14.04 on mn-sandbox-ucsb-1. The error message is:
`BUILD FAILED
/home/dev/tao/project/metacat/build.xml:1712: /home/dev/tao/project/metacat/boot does not exist.`
The maven version is:
`tao@mn-sandbox-ucsb-1:~/project/metacat$ mvn -version`
`Apache Maven 2.2.1 (rdebian-14)
`

**Comment by amoeba** [comment]
> The mn-demo-6 was just upgraded to Ubuntu 18.04 and the maven was removed. After I reinstall maven, it works. My bad.

Did the setMavenHome task fail with a helpful error message or fail in a weird way?

> However, the branch doesn't work with Ubuntu 14.04 on mn-sandbox-ucsb-1. The error message is:
BUILD FAILED /home/dev/tao/project/metacat/build.xml:1712: /home/dev/tao/project/metacat/boot does not exist.

Weird. Any chance I can get access to that box? You don't have a `$MAVEN_HOME` var set do you?

**Comment by taojing2002** [comment]
I don't have a `MAVEN_HOME` setting. Would you please ask Nick to create an account on that machine for you?

**Comment by amoeba** [comment]
Sure 👍

**Comment by amoeba** [comment]
This is caused behavior that Maven 2 (end of lifed in 2009). So I expect this ant target will work for maven 3 and newer. I'll see if I can find a nice way of handling Maven 2.

**Comment by amoeba** [comment]
@taojing2002 I pushed a fix and tested on mn-sandbox-1 and it seems to work. Thanks for catching that edge case.

**Comment by taojing2002** [comment]
Really? I just pulled the update and ran again, but still got an error:
`BUILD FAILED`
`/home/dev/tao/project/metacat/build.xml:1732: /usr/share/maven2/boot/boot does not exist.`
` git status`
`On branch feature-autodetect-maven`
`Your branch is up-to-date with 'origin/feature-autodetect-maven'.`

`nothing to commit, working directory clean`

**Comment by amoeba** [comment]
Yeah:

```sh
mecum@mn-sandbox-ucsb-1:~$ git clone https://github.com/nceas/metacat
fatal: destination path 'metacat' already exists and is not an empty directory.
mecum@mn-sandbox-ucsb-1:~$ mv metacat metacat-targz
mecum@mn-sandbox-ucsb-1:~$ git clone https://github.com/nceas/metacat
Cloning into 'metacat'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 24323 (delta 5), reused 14 (delta 4), pack-reused 24297
Receiving objects: 100% (24323/24323), 138.82 MiB | 64.09 MiB/s, done.
Resolving deltas: 100% (13611/13611), done.
Checking connectivity... done.
mecum@mn-sandbox-ucsb-1:~$ cd metacat
mecum@mn-sandbox-ucsb-1:~/metacat$ git fetch --all
Fetching origin
mecum@mn-sandbox-ucsb-1:~/metacat$ git checkout origin/feature-autodetect-maven
Note: checking out 'origin/feature-autodetect-maven'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 8c035cb... Add support for deblike+maven2 to build.xml's setMavenHome target
mecum@mn-sandbox-ucsb-1:~/metacat$ git l^C
mecum@mn-sandbox-ucsb-1:~/metacat$ ant setMavenHome
Buildfile: /home/mecum/metacat/build.xml

setMavenHome:
     [exec] Result: 1
     [echo] Setting Maven home (maven.home) to '/usr/share/maven2/boot'.

BUILD SUCCESSFUL
Total time: 0 seconds
```

**Comment by taojing2002** [comment]
So my error message shows:
`/home/dev/tao/project/metacat/build.xml:1732: /usr/share/maven2/boot/boot does not exist`
You see, there are two `boot` at the end of the file path. I guess somehow the maven home shouldn't have the `boot` at the end of file path.

**Comment by amoeba** [comment]
I can run your script fine:

```sh
mecum@mn-sandbox-ucsb-1:/home/dev/tao/project/metacat$ ant setMavenHome
Buildfile: /home/dev/tao/project/metacat/build.xml

setMavenHome:
     [exec] Result: 1
     [echo] Setting Maven home (maven.home) to '/usr/share/maven2/boot'.

BUILD SUCCESSFUL
Total time: 0 seconds
```

How are you running that?

**Comment by taojing2002** [comment]
The command `ant setMavenHome` works to me.
But the command `ant compile` fails. May you try this command as well?

**Comment by amoeba** [comment]
Ah, I see. It's gotta be something with maven2. I'll look into it.

**Comment by amoeba** [comment]
Alright, can you give it a whirl now?

**Comment by taojing2002** [comment]
Works great! I will do some test, then merge it to dev-2.10. Thank you, 
Bryce!

**Comment by amoeba** [comment]
Thanks for the help testing it out!

**Comment by taojing2002** [comment]
You are welcome. Thank you for fix the issue!

**Pull request merged**
